### ISSUE TITLE
kumocloud variable referenced before assignment bug

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#205]
DEBUG: refreshing data from cloud
Timeout querying KumoCloud: HTTPSConnectionPool(host='geo-c.kumocloud.com', port=443): Read timed out. (read timeout=5)
Traceback (most recent call last):
  File "C:\Users\cjkro\onedrive\documents\github\ThermostatSupervisor\supervise.py", line 176, in <module>
    main(tstat_type, zone_input)
  File "C:\Users\cjkro\onedrive\documents\github\ThermostatSupervisor\supervise.py", line 146, in main
    Zone.refresh_zone_info()
  File "C:\Users\cjkro\onedrive\documents\github\ThermostatSupervisor\kumocloud.py", line 409, in refresh_zone_info
    self.Thermostat._fetch_if_needed() \
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\site-packages\pykumo\pykumo.py", line 523, in _fetch_if_needed
    if response.ok:
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by cjkrolak** [comment]
ticket opened in originator's repo:  https://github.com/dlarrick/pykumo/issues/18
