### ISSUE TITLE
SHT31 internal server error

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#248]
happened after session 3, poll 410:

Traceback (most recent call last):
  File "supervise.py", line 191, in <module>
    main(api.user_inputs["thermostat_type"], api.user_inputs["zone"])
  File "supervise.py", line 140, in main
    flag_all_deviations=revert_all_deviations)
  File "/home/pi/github/ThermostatSupervisor/thermostat_common.py", line 222, in get_current_mode
    self.query_thermostat_zone()
  File "/home/pi/github/ThermostatSupervisor/thermostat_common.py", line 116, in query_thermostat_zone
    self.humidity_is_available = self.get_is_humidity_supported()
  File "/home/pi/github/ThermostatSupervisor/sht31.py", line 301, in get_is_humidity_supported
    return self.get_display_humidity() is not None
  File "/home/pi/github/ThermostatSupervisor/sht31.py", line 293, in get_display_humidity
    raw_humidity = self.get_metadata(self.humidityfield)
  File "/home/pi/github/ThermostatSupervisor/sht31.py", line 266, in get_metadata
    self.get_metadata(parameter, retry=False)
  File "/home/pi/github/ThermostatSupervisor/sht31.py", line 271, in get_metadata
    (parameter, r.json())) from e
Exception: FATAL ERROR: SHT31 server response did not contain key 'Humidity(%RH) mean', raw response={'message': 'Internal Server Error'}

**Comment by cjkrolak** [comment]
failure is due to a get error on the host side:
173.26..xxx.xxx - - [03/Dec/2021 07:19:48] "GET / HTTP/1.1" 200 -
[2021-12-03 07:19:48,900] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "sht31_flask_server.py", line 112, in get
    return helper.get()
  File "sht31_flask_server.py", line 67, in get
    data = bus.read_i2c_block_data(i2c_address, 0x00, 6)

**Comment by cjkrolak** [comment]
restarting cmd prompt and rebooting pi did not resolve the issue, may need to troubleshoot locally.  Remote IC test #137 may be helpful at further diagnosing this issue

**Comment by cjkrolak** [comment]
soft power cycle (remote) did not resolve the issue, but hard power cycle at the wall did resolve the issue

**Comment by cjkrolak** [comment]
this issue still requires a hard power cycle to clear, keeping issue open in hopes that a soft reset can be figured out to clear this error remotely.

**Comment by cjkrolak** [comment]
re-opening issue

**Comment by cjkrolak** [comment]
sudo i2cdetect -y 1 in the failing state is showing that i2c is not showing up at all, possible hardware issue.  Goal of this ticket is to either prevent the issue or design a remote recovery process that does not require a local power cycle to clear.

**Comment by cjkrolak** [comment]
tried this i2c reset sequence but was unsuccessful:

disable the I2C driver with
sudo rmmod i2c_dev: seemed to work
sudo rmmod i2c_bcm2835: hung
sudo i2cdetect -y 1:  Could not open file `/dev/i2c-1' or `/dev/i2c/1'
lsmod:   i2c_bcm3835 used_by = -1
re-enable it with
sudo modprobe i2c_bcm2835:  hung
sudo modprobe i2c_dev: didn't get this far

http://www.pibits.net/amp/learning/resetting-i2c-driver-raspberry-pi.php

**Comment by cjkrolak** [comment]
interesting thread on auto recover stuck bus:  https://forums.raspberrypi.com/viewtopic.php?t=326603

**Comment by cjkrolak** [comment]
failure detected again on 12/14/24:

```
  File "/home/pi/.local/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/sht31_flask_server.py", line 645, in get
    return helper.get()
           ^^^^^^^^^^^^
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/sht31_flask_server.py", line 319, in get
    self.send_i2c_cmd(bus, sht31_config.I2C_ADDRESS, cs_enabled_high)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/sht31_flask_server.py", line 179, in send_i2c_cmd
    raise exc
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/sht31_flask_server.py", line 173, in send_i2c_cmd
    bus.write_i2c_block_data(i2c_addr, register, data)
  File "/home/pi/.local/lib/python3.12/site-packages/smbus2/smbus2.py", line 645, in write_i2c_block_data
    ioctl(self.fd, I2C_SMBUS, msg)
TimeoutError: [Errno 110] Connection timed ou
```

**Comment by cjkrolak** [comment]
related to #478

**Comment by cjkrolak** [comment]
remote sequence to resolve i2c detection issue:

```
<sht31address>:<port>/i2c_recovery
reboot sht31 and start sht31 server
<sht31address>:<port>/diag - command will fail worse than before
reboot sht31 a second time and start sht31 server
<sht31address>:<port>/diag - command works
```

**Comment by cjkrolak** [comment]
ran recovery on 1/26/25 with one reboot and server was failing again within a day, probably should do a hard reboot next time I am local to the server.
