### ISSUE TITLE
address JSONDecodeError in Honeywell pyhtcc.py

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#29]
Traceback (most recent call last):
  File "supervise.py", line 153, in <module>
    main(tstat_type)
  File "supervise.py", line 122, in main
    zone.refresh_zone_info()
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 69, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 343, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

occurred after 99 good polls

**Comment by cjkrolak** [comment]
added a try/catch and retry in this commit
