### ISSUE TITLE
intermittent 3m timeouts

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#353]
even with a 30 second timeout the 3m thermostats can timeout intermittently, not sure if it is on the thermostat side or the client side.  This week observed the issue with raspberrypi-0, traceback is below, mode was 2 seconds but evidently had a read within the first 30 measurements that was over 30 seconds and timed out:

Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/mmm.py", line 763, in <module>
    meas_data = Zone.measure_thermostat_response_time(measurements)
  File "/home/pi/github/ThermostatSupervisor/thermostat_common.py", line 730, in measure_thermostat_response_time
    func()  # target command
  File "/home/pi/github/ThermostatSupervisor/mmm.py", line 245, in get_display_temp
    return float(self.device_id.temp['raw'])
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/fields.py", line 46, in __get__
    envelope = json.loads(response.read().decode('utf-8'))
  File "/usr/lib/python3.9/http/client.py", line 465, in read
    return self._readall_chunked()
  File "/usr/lib/python3.9/http/client.py", line 572, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.9/http/client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.9/http/client.py", line 515, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by cjkrolak** [comment]
plan for now is to increase the number of measurements for diagnostics because I am not measuring these timeouts during investigation using 2 different clients.

I also will extend the timeout from 30 to 60 seconds, this is not a hang concern right now since the default polling time is 10 minutes.  If this issue continues to be a problem may consider overriding radiotherm.fields.__get__ to include a retry.
