### ISSUE TITLE
add additional timestamps during timeout retries

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#395]
28 minutes elapsed between these retries, should have been closer to a minute.  Need additional timestamps to help understand all the time loss.

2022-01-21 09:34:20: (session:1, poll:19) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 09:44:29: (session:1, poll:20) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 09:54:39: (session:1, poll:21) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:04:49: (session:1, poll:22) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:14:59: (session:1, poll:23) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:25:10: (session:1, poll:24) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:35:19: (session:1, poll:25) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:45:29: (session:1, poll:26) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=30% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 10:55:40: (session:1, poll:27) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=31% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:05:49: (session:1, poll:28) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=31% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:15:58: (session:1, poll:29) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=31% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:26:08: (session:1, poll:30) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:36:18: (session:1, poll:31) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:46:27: (session:1, poll:32) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 11:56:36: (session:1, poll:33) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:06:46: (session:1, poll:34) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:16:56: (session:1, poll:35) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:27:07: (session:1, poll:36) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:37:16: (session:1, poll:37) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:47:27: (session:1, poll:38) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 12:57:40: (session:1, poll:39) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=32% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:07:57: (session:1, poll:40) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:18:10: (session:1, poll:41) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:28:19: (session:1, poll:42) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:38:37: (session:1, poll:43) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:48:48: (session:1, poll:44) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 13:58:58: (session:1, poll:45) HEAT_MODE [HEAT_MODE deviation] act temp=68.0°F, act humidity=34% RH (temporary), set point=68.0°F, tolerance=2.0°F, override=72.0°F
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: honeywell HEAT_MODE deviation alert on zone 0
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!

*** honeywell HEAT_MODE deviation detected on zone 0, reverting thermostat to heat schedule ***

2022-01-21 14:09:11: (session:1, poll:46) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 14:19:20: (session:1, poll:47) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 14:29:29: (session:1, poll:48) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 14:39:38: (session:1, poll:49) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 14:49:48: (session:1, poll:50) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 14:59:58: (session:1, poll:51) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 15:10:09: (session:1, poll:52) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 15:20:18: (session:1, poll:53) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 15:30:28: (session:1, poll:54) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 15:40:38: (session:1, poll:55) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 15:50:47: (session:1, poll:56) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:00:57: (session:1, poll:57) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:11:07: (session:1, poll:58) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:21:16: (session:1, poll:59) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:31:25: (session:1, poll:60) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:41:34: (session:1, poll:61) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 16:51:44: (session:1, poll:62) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 17:01:54: (session:1, poll:63) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 17:12:03: (session:1, poll:64) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=34% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 17:22:15: (session:1, poll:65) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=35% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 17:32:25: (session:1, poll:66) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=35% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2022-01-21 17:42:35: (session:1, poll:67) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=35% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
[log_msg]: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mytotalconnectcomfort.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 700, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 195, in get_zones_info
    result = self._post_zone_list_data(page_num)
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 324, in _post_zone_list_data
    return self.session.post(f'https://mytotalconnectcomfort.com/portal/Device/GetZoneListData?locationId={self._locationId}&page={page_num}', headers={'X-Requested-With': 'XMLHttpRequest'})
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mytotalconnectcomfort.com', port=443): Read timed out. (read timeout=None)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 60 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 2 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
2022-01-21 18:10:22: (session:1, poll:68) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=35% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F

**Comment by cjkrolak** [comment]
another example with 30 minutes between good measurements:

2022-01-22 03:48:00: (session:1, poll:123) HEAT_MODE [following schedule] act temp=66.0°F, act humidity=35% RH, set point=66.0°F, tolerance=2.0°F, override=66.0°F
[log_msg]: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mytotalconnectcomfort.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 700, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 195, in get_zones_info
    result = self._post_zone_list_data(page_num)
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 324, in _post_zone_list_data
    return self.session.post(f'https://mytotalconnectcomfort.com/portal/Device/GetZoneListData?locationId={self._locationId}&page={page_num}', headers={'X-Requested-With': 'XMLHttpRequest'})
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mytotalconnectcomfort.com', port=443): Read timed out. (read timeout=None)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 60 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 2 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
2022-01-22 04:15:43: (session:1, poll:124) HEAT_MODE [following schedule] act temp=66.0°F, act humidity=35% RH, set point=66.0°F, tolerance=2.0°F, override=66.0°F
