### ISSUE TITLE
get_schedule_heat_sp fails on 3m50

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#444]
issue happened on zone 0 but not zone 1, I have seen this issue a few times.

2022-01-31 00:48:33: (session:3, poll:26) HEAT_MODE [following schedule] act temp=58.5°F, set point=68.0°F, tolerance=2.0°F, override=44.0°F
DEBUG in set_mode, target_mode=OFF_MODE, doing nothing
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 225, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 210, in exec_supervise
    supervisor(api.user_inputs["thermostat_type"], api.user_inputs["zone"])
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 142, in supervisor
    current_mode_dict = Zone.get_current_mode(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 268, in get_current_mode
    self.query_thermostat_zone()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 148, in query_thermostat_zone
    self.schedule_setpoint = int(self.get_schedule_heat_sp())
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/mmm.py", line 535, in get_schedule_heat_sp
    result = self.get_schedule_setpoint(self.device_id.program_heat)
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/fields.py", line 47, in __get__
    self.validate_response(response, envelope)
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/validate.py", line 28, in validate_response
    raise AttributeError('Error message from thermostat: %s' % content[error_field])
AttributeError: Error message from thermostat: -1

**Comment by cjkrolak** [comment]
another occurrence:

2022-12-28 00:07:46: (tstat:mmm50, zone:0, session:2, poll:30) HEAT_MODE [following schedule] act temp=58.0°F, set point=66.0°F, tolerance=2.0°F, override=44.0°F
revert_thermostat_mode: target_mode='UNKNOWN_MODE', doing nothing.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 133, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 113, in exec_supervise
    supervisor(api.uip.get_user_inputs(api.uip.parent_keys[0],
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 76, in supervisor
    measurement = Zone.supervisor_loop(Thermostat, session_count,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1004, in supervisor_loop
    current_mode_dict = self.get_current_mode(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 275, in get_current_mode
    self.query_thermostat_zone()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 155, in query_thermostat_zone
    self.schedule_setpoint = int(self.get_schedule_heat_sp())
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/mmm.py", line 543, in get_schedule_heat_sp
    result = self.get_schedule_setpoint(self.device_id.program_heat)
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/fields.py", line 47, in __get__
    self.validate_response(response, envelope)
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/validate.py", line 28, in validate_response
    raise AttributeError('Error message from thermostat: %s' % content[error_field])
AttributeError: Error message from thermostat: -1

**Comment by cjkrolak** [comment]
3m thermostat is obsolete due to server EOL, closing ticket without fix.
