### ISSUE TITLE
cleanup codebase with autopep8

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#453]
autopep8 --in-place --aggressive --aggressive --aggressive --verbose <filename>

**Comment by cjkrolak** [comment]
integration testing failed for 4 tests related to sht31, need to check develop branch for comparison...
======================================================================
ERROR: test_a_thermostat_basic_checkout (test_sht31_integration.FunctionalIntegrationTest)
Verify thermostat_basic_checkout on target thermostat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 275, in get_metadata
    return response.json()[parameter]
KeyError: 'Temp(F) mean'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 275, in get_metadata
    return response.json()[parameter]
KeyError: 'Temp(F) mean'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\tests\unit_test_common.py", line 198, in test_a_thermostat_basic_checkout
    tc.thermostat_basic_checkout(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 957, in thermostat_basic_checkout
    Zone.display_basic_thermostat_summary()
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 818, in display_basic_thermostat_summary
    util.temp_value_with_units(self.get_display_temp()),
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 321, in get_display_temp
    return float(self.get_metadata(self.tempfield))
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 305, in get_metadata
    self.get_metadata(parameter, retry=False)
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 307, in get_metadata
    raise Exception("FATAL ERROR: SHT31 server "
Exception: FATAL ERROR: SHT31 server response did not contain key 'Temp(F) mean', raw response={'message': 'Internal Server Error'}

======================================================================
ERROR: test_get_meta_data (test_sht31_integration.FunctionalIntegrationTest)
Verify get_metadata().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\tests\unit_test_common.py", line 254, in test_get_meta_data
    metadata = self.Thermostat.get_metadata(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 114, in get_metadata
    return raw_json[parameter]
KeyError: 'Temp(F) mean'

======================================================================
ERROR: test_supervise (test_sht31_integration.SuperviseIntegrationTest)
Verify supervisor loop on target thermostat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 275, in get_metadata
    return response.json()[parameter]
KeyError: 'Temp(F) mean'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 275, in get_metadata
    return response.json()[parameter]
KeyError: 'Temp(F) mean'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\tests\unit_test_common.py", line 276, in test_supervise
    return_status = sup.exec_supervise(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\supervise.py", line 210, in exec_supervise
    supervisor(api.user_inputs["thermostat_type"], api.user_inputs["zone"])
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\supervise.py", line 142, in supervisor
    current_mode_dict = Zone.get_current_mode(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 268, in get_current_mode
    self.query_thermostat_zone()
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 133, in query_thermostat_zone
    self.display_temp = self.validate_numeric(self.get_display_temp(),
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 321, in get_display_temp
    return float(self.get_metadata(self.tempfield))
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 305, in get_metadata
    self.get_metadata(parameter, retry=False)
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 307, in get_metadata
    raise Exception("FATAL ERROR: SHT31 server "
Exception: FATAL ERROR: SHT31 server response did not contain key 'Temp(F) mean', raw response={'message': 'Internal Server Error'}

======================================================================
ERROR: test_supervisor (test_supervise.Test)
Verify main supervisor loop.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021B0C485990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.86.15', port=5000): Max retries exceeded with url: /?measurements=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B0C485990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\tests\test_supervise.py", line 47, in test_supervisor
    sup.supervisor(sht31_config.ALIAS, sht31_config.UNIT_TEST_ZONE)
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\supervise.py", line 142, in supervisor
    current_mode_dict = Zone.get_current_mode(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 268, in get_current_mode
    self.query_thermostat_zone()
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 133, in query_thermostat_zone
    self.display_temp = self.validate_numeric(self.get_display_temp(),
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 321, in get_display_temp
    return float(self.get_metadata(self.tempfield))
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 255, in get_metadata
    raise ex
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 250, in get_metadata
    response = requests.get(self.url)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.86.15', port=5000): Max retries exceeded with url: /?measurements=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B0C485990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

======================================================================
FAIL: test_SHT31_FlaskServer_All_Pages (test_sht31_flask_server.IntegrationTest)
Confirm all pages return data from Flask server.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\tests\test_sht31_flask_server.py", line 74, in test_SHT31_FlaskServer_All_Pages
    self.assertTrue(expected_key in return_data,
AssertionError: False is not true : test_case 'production': key 'measurements' was not found in return data: {'message': 'Internal Server Error'}

----------------------------------------------------------------------
Ran 97 tests in 480.423s

FAILED (failures=1, errors=4, skipped=31)
