### ISSUE TITLE
permission error when running docker image on pi4

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#455]
docker run --env-file supervisor-env.txt cjkrolak/thermostatsupervisor emulator 0

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/thermostatsupervisor/supervise.py", line 225, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/usr/src/app/thermostatsupervisor/supervise.py", line 210, in exec_supervise
    supervisor(api.user_inputs["thermostat_type"], api.user_inputs["zone"])
  File "/usr/src/app/thermostatsupervisor/supervise.py", line 119, in supervisor
    time0 = time.time()  # connection timer
PermissionError: [Errno 1] Operation not permitted

**Comment by cjkrolak** [comment]
running in privileged mode may help:  --privileged 
specifying device may help:  --device=/dev/sdb

https://stackoverflow.com/questions/35617912/why-does-docker-container-prompt-permission-denied

**Comment by cjkrolak** [comment]
both pi0 and pi4 are hanging on docker run command, once you ctrl-c to cancel the job the data is dumped to stdout.  This issue was not observed initially on pi4.

**Comment by cjkrolak** [comment]
docker run --rm -it --env-file supervisor-env.txt cjkrolak/thermostatsupervisor emulator 0 60 works with interactive option -it

**Comment by cjkrolak** [comment]
pi4 still requires the --privileged flag to avoid permission errors, sudo does not work as a work-around
