### ISSUE TITLE
PermissionError running Flaskserver from IDE on Raspberry PI

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#53]
Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/flaskserver.py", line 46, in <module>
    app.run(host='127.0.0.1', port=flask_port)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

**Comment by cjkrolak** [comment]
this permission error is a result of attempting to bind port 80 when not in sudo/root mode.

sudo thonny will invoke Thonny in root and then you won't see this error.

https://stackoverflow.com/questions/51396047/running-flask-on-port-80-in-linux

**Comment by cjkrolak** [comment]
using port other than 80 will also mitigate this issue.
