### ISSUE TITLE
Honeywell crash due to connection issue

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#544]
Honeywell crash due to connection issue, need mitigation or alert:
[log_msg]: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

**Comment by cjkrolak** [comment]
already have 3 retries in place before giving up, but this does not mitigate crash for long duration connection issues, maybe a lengthening retry delay algorithm would be better to allow for up to 24 hour connection issue.
