### ISSUE TITLE
sht31 flask server won't launch due to key error

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#547]
parent key is missing from call.

SHT31 sensor Flask server
running on Python version 3.9
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/sht31_flask_server.py", line 687, in <module>
    debug = uip.get_user_inputs("debug")
TypeError: get_user_inputs() missing 1 required positional argument: 'child_key'

**Comment by cjkrolak** [comment]
issue resolved
