### ISSUE TITLE
zone runtime input parsed as str, causing key error

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#563]
C:\github\ThermostatSupervisor>python -m thermostatsupervisor.sht31 0
running on Python version 3.10
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\sht31.py", line 498, in <module>
    api.uip = api.UserInputs(argv_list=None,
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_api.py", line 92, in __init__
    super().__init__(argv_list, help_description, suppress_warnings,
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\utilities.py", line 398, in __init__
    self.parse_runtime_parameters(argv_list)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\utilities.py", line 470, in parse_runtime_parameters
    self.dynamic_update_user_inputs()
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_api.py", line 283, in dynamic_update_user_inputs
    SUPPORTED_THERMOSTATS[thermostat_type]["zones"]
KeyError: '0'

**Comment by cjkrolak** [comment]
issue affects input list, not named parameters

**Comment by cjkrolak** [comment]
root cause was end user not including thermostat_type in the runtime parameters, so zone number was being interpreted as the thermostat type.  I added two KeyError exception messages to make the issue more explicitly obvious.
