### ISSUE TITLE
docker build failing due to bunch install issue

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#577]
https://github.com/cjkrolak/ThermostatSupervisor/actions/runs/3414654172/jobs/5682890653

#22 [linux/amd64 4/5] RUN pip3 install -r requirements.txt
#22 3.349 Collecting bunch>=1.0.1
#22 3.393   Downloading bunch-1.0.1.zip (11 kB)
#22 3.402   Preparing metadata (setup.py): started
#22 4.393   Preparing metadata (setup.py): finished with status 'error'
#22 4.409   error: subprocess-exited-with-error
#22 4.409   
#22 4.409   × python setup.py egg_info did not run successfully.
#22 4.409   │ exit code: 1
#22 4.409   ╰─> [7 lines of output]
#22 4.409       Traceback (most recent call last):
#22 4.409         File "<string>", line 2, in <module>
#22 4.409         File "<pip-setuptools-caller>", line 34, in <module>
#22 4.409         File "/tmp/pip-install-yovzzhv_/bunch_bbdae4c93a6544209182806454c0d8f8/setup.py", line 11, in <module>
#22 4.409           package_file = open(join(HERE, 'bunch/__init__.py'), 'rU')
#22 4.409                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#22 4.409       ValueError: invalid mode: 'rU'
#22 4.409       [end of output]
#22 4.409   
#22 4.409   note: This error originates from a subprocess, and is likely not a problem with pip.
#22 4.412 error: metadata-generation-failed
#22 4.412 
#22 4.412 × Encountered error while generating package metadata.
#22 4.412 ╰─> See above for output.
#22 4.412 
#22 4.412 note: This is an issue with the package mentioned above, not pip.
#22 4.412 hint: See above for details.
#22 4.547 
#22 4.547 [notice] A new release of pip available: 22.3 -> 22.3.1
#22 4.547 [notice] To update, run: pip install --upgrade pip
#22 ERROR: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1

**Comment by cjkrolak** [comment]
this issue has been failing since 11/7/22. Last passing run does not have a log anymore for comparison.

**Comment by cjkrolak** [comment]
bunch 1.0.1 is incompatible with python 3.11, set python version in Dockerfile to 3.10 to mitigate the issue.
