### ISSUE TITLE
socket timeout on 3m50

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#582]
```
2023-01-13 13:12:44: (tstat:mmm50, zone:0, session:1, poll:82) HEAT_MODE [following schedule] act temp=68.5°F, set point=69.0°F, tolerance=2.0°F, override=69.0°F
revert_thermostat_mode: target_mode='UNKNOWN_MODE', doing nothing.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 133, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 113, in exec_supervise
    supervisor(api.uip.get_user_inputs(api.uip.parent_keys[0],
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 76, in supervisor
    measurement = Zone.supervisor_loop(Thermostat, session_count,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1004, in supervisor_loop
    current_mode_dict = self.get_current_mode(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 275, in get_current_mode
    self.query_thermostat_zone()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 155, in query_thermostat_zone
    self.schedule_setpoint = int(self.get_schedule_heat_sp())
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/mmm.py", line 543, in get_schedule_heat_sp
    result = self.get_schedule_setpoint(self.device_id.program_heat)
  File "/home/pi/.local/lib/python3.9/site-packages/radiotherm/fields.py", line 46, in __get__
    envelope = json.loads(response.read().decode('utf-8'))
  File "/usr/lib/python3.9/http/client.py", line 465, in read
    return self._readall_chunked()
  File "/usr/lib/python3.9/http/client.py", line 572, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.9/http/client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.9/http/client.py", line 515, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
pi@raspberrypi0:~/github/ThermostatSupervisor $ 
```

**Comment by cjkrolak** [comment]
3m thermostat is obsolete due to server EOL, closing ticket without fix.
