### ISSUE TITLE
Honeywell supervise sequence hung

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#584]
Honeywell hung on pi4 for 9 days until detected, maybe at the url open command
```
2023-01-17 15:33:35: (tstat:honeywell, zone:0, session:13, poll:105) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=44% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
revert_thermostat_mode: target_mode='UNKNOWN_MODE', doing nothing.



^CTraceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 133, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 113, in exec_supervise
    supervisor(api.uip.get_user_inputs(api.uip.parent_keys[0],
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 76, in supervisor
    measurement = Zone.supervisor_loop(Thermostat, session_count,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1004, in supervisor_loop
    current_mode_dict = self.get_current_mode(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 275, in get_current_mode
    self.query_thermostat_zone()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 154, in query_thermostat_zone
    self.current_setpoint = int(self.get_heat_setpoint_raw())
  File "/home/pi/.local/lib/python3.9/site-packages/pyhtcc/pyhtcc.py", line 169, in get_heat_setpoint_raw
    def get_current_temperature_raw(self) -> int:
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 725, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 247, in get_zones_info
    result = self._get_check_data_session(device_id)
  File "/home/pi/.local/lib/python3.9/site-packages/pyhtcc/pyhtcc.py", line 413, in _get_check_data_session
    )
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
```

**Comment by cjkrolak** [comment]
I have not seen this error in a while, de-prioritizing issue

**Comment by cjkrolak** [comment]
duplicate of #40 closing this ticket
