### ISSUE TITLE
increase retry count from 1 to 3 for JSONDecode errors

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#59]
Continue to have JSON decode errors, most of the time a single retry is mitigating the issue, but here's another failure during the 34th session.  Increasing retry count from 1 to 3 to reduce the probability of such failure.

2021-06-08 00:36:16: (session:34, poll:130) COOL MODE [following schedule] actual=72, set point=72, override=72
DEBUG: main: refreshing zone...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 483, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 179, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, probably a connection issue, waiting 30 seconds and then retrying once...
Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 483, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 179, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "supervise.py", line 171, in <module>
    main(tstat_type)
  File "supervise.py", line 128, in main
    zone.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 494, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()  # retry once
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 179, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cjkrolak** [comment]
branch 59 merged into main and is now in production, will need to test for a while to determine how effective this change is and to ensure that the email notifications are working properly.

**Comment by cjkrolak** [comment]
able to reach 9 sessions with this increased retry count, closing ticket for now.
