### ISSUE TITLE
blink: AttributeError: 'NoneType' object has no attribute 'base_url'

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#628]
intermittent failure running blink checkout

```
Login endpoint failed. Try again later.
Cannot setup Blink platform.
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 370, in <module>
    tc.thermostat_basic_checkout(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1115, in thermostat_basic_checkout
    Thermostat, Zone = create_thermostat_instance(thermostat_type, zone,
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1079, in create_thermostat_instance
    Thermostat = ThermostatClass(zone)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 57, in __init__
    self.blink.auth.send_auth_key(self.blink, self.bl_2fa)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\blinkpy\auth.py", line 240, in send_auth_key
    response = api.request_verify(self, blink, key)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\site-packages\blinkpy\api.py", line 60, in request_verify
    url = f"{blink.urls.base_url}/api/v4/account/{blink.account_id}/client/{blink.client_id}/pin/verify"
AttributeError: 'NoneType' object has no attribute 'base_url'
```

**Comment by cjkrolak** [comment]
this issue is still happening on AzDO (#638) but is not occurring locally anymore (or it's intermittent).

**Comment by cjkrolak** [comment]
this is intermittent both locally and through AzDO
