### ISSUE TITLE
blink: ValueError: Camera zone 2(front yard) was not found

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#629]
intermittent error running blink checkout

```
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 370, in <module>
    tc.thermostat_basic_checkout(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1115, in thermostat_basic_checkout
    Thermostat, Zone = create_thermostat_instance(thermostat_type, zone,
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1080, in create_thermostat_instance
    Thermostat.print_all_thermostat_metadata(zone)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 144, in print_all_thermostat_metadata
    self.exec_print_all_thermostat_metadata(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 58, in exec_print_all_thermostat_metadata
    return_data = func(*args)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 112, in get_all_metadata
    return self.get_metadata(zone, None, debug)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\blink.py", line 133, in get_metadata
    raise ValueError(f"Camera zone {zone}({zone_name}) was not found")
ValueError: Camera zone 2(front yard) was not found
```

**Comment by cjkrolak** [comment]
I have not seen this issue in a while, maybe due to a disconnected camera.  I will leave the issue open but de-prioritize it.

**Comment by cjkrolak** [comment]
closing this issue as no longer able to reproduce
