### ISSUE TITLE
blink: Did not receive valid response from server.

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#640]
not sure if this is a real error or not, shows up on every login

**Comment by cjkrolak** [comment]
it seems like the server is complaining after too many authentications, this is an intermittent failure

**Comment by cjkrolak** [comment]
appears to be a 2fa error:

```
Did not receive valid response from server.
Traceback (most recent call last):
  File "C:\github\ThermostatSupervisor\..\blinkpy\blinkpy\auth.py", line 243, in send_auth_key
    blink.available = json_resp["valid"]
                      ~~~~~~~~~^^^^^^^^^
KeyError: 'valid'

DEBUG: response=<Response [401]>, type=<class 'requests.models.Response'>
```

**Comment by cjkrolak** [comment]
I tried both the key sent via text and one sent in 2021 via email, both as string and int, none worked.  This error does not seem to prevent access to the cameras.

**Comment by cjkrolak** [comment]
error seems to be legitamite authorization issue, here's verbose traceback:

```
Did not receive valid response from server.
Traceback (most recent call last):
  File "C:\github\ThermostatSupervisor\..\blinkpy\blinkpy\auth.py", line 219, in send_auth_key
    blink.available = json_resp["valid"]
                      ~~~~~~~~~^^^^^^^^^
KeyError: 'valid'

DEBUG: response=854590, type=<class 'str'>
DEBUG: response=<ClientResponse(https://rest-u043.immedia-semi.com/api/v4/account/241134/client/581123/pin/verify) [401 Unauthorized]>
<CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '44', 'Connection': 'keep-alive', 'Date': 'Tue, 07 Nov 2023 12:24:15 GMT', 'Client-Verified': '0', 'Server': 'nginx + Phusion Passenger(R)', 'Status': '401 Unauthorized', 'X-Blink-Served-By': 'i-0ec8cf8179e13aa5a', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'Phusion Passenger(R)', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 02b00a121cd210844e6b946bc2d15b26.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MSP50-C2', 'X-Amz-Cf-Id': 'me1WNJiugQgXUGAIiKf9NbXQtov5xnr0OlJB0fwhRlx7WYEiR5xM4w==')>
, type=<class 'aiohttp.client_reqrep.ClientResponse'>
zone: 8, name: 8, temp: None
```

**Comment by cjkrolak** [comment]
this issue may be related to https://github.com/fronzbot/blinkpy/issues/418 however that ticket claims that the 2FA validation was fixed by blink at some point, I'm still seeing bad 2FA NOT preventing access to camera data.

I tried multiple 2FA codes and none of them are being accepted by blink.  This is a nuisance error message at this point.

**Comment by cjkrolak** [comment]
error message today:  Did not receive valid response from server. Error: 'valid'

**Comment by cjkrolak** [comment]
2FA is now working after fixes in #1459, closing this ticket as cannot reproduce.
