### ISSUE TITLE
kumocloud KeyError

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#652]
```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 670, in <module>
    tc.thermostat_basic_checkout(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1136, in thermostat_basic_checkout
    Zone.display_basic_thermostat_summary()
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 831, in display_basic_thermostat_summary
    self.get_system_switch_position())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 534, in get_system_switch_position
    if not self.is_power_on():
           ^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 414, in is_power_on
    return self.get_parameter('power', 'reportedCondition', default_val=0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 224, in get_parameter
    return_val = parent_dict[key]
                 ~~~~~~~~~~~^^^^^
KeyError: 'power'
```

**Comment by cjkrolak** [comment]
KeyErrors caused by off mode, exposed a few code bugs.
