### ISSUE TITLE
nest: CSRF mismatch error when authenticating

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#701]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 659, in <module>
    tc.thermostat_basic_checkout(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1132, in thermostat_basic_checkout
    Thermostat, Zone = create_thermostat_instance(thermostat_type, zone,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1095, in create_thermostat_instance
    Thermostat = ThermostatClass(zone, verbose=verbose)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 116, in __init__
    self.zone_name = self.get_zone_name()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 126, in get_zone_name
    devices = self.thermostat_obj.get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\nest\nest.py", line 307, in get_devices
    for device in self._devices:
                  ^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\nest\nest.py", line 288, in _devices
    self._devices_value = self._request('GET', '')['devices']
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\nest\nest.py", line 273, in _request
    self.__reauthorize()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\nest\nest.py", line 232, in __reauthorize
    token = self._client.fetch_token(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_uri_response(
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python312\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 278, in parse_authorization_code_response
    raise MismatchingStateError()
oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.
```

**Comment by cjkrolak** [comment]
root cause was due to credentials.json using GCLOUD_PROJECT_ID instead of project id UUID for the project_id field.  json file updated, no code changes needed for this fix.
