### ISSUE TITLE
kumocloud: IndexError during basic checkout due to bad credentials

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#730]
issue is due to bad KUMO env parameters on pi4.  Error message should be cleaner.

```
No JSON returned from KumoCloud; check credentials?
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/kumocloud.py", line 734, in <module>
    tc.thermostat_basic_checkout(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1146, in thermostat_basic_checkout
    Thermostat, Zone = create_thermostat_instance(thermostat_type, zone,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1111, in create_thermostat_instance
    Thermostat.print_all_thermostat_metadata(zone)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/kumocloud.py", line 172, in print_all_thermostat_metadata
    self.exec_print_all_thermostat_metadata(
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 63, in exec_print_all_thermostat_metadata
    return_data = func(*args)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/kumocloud.py", line 106, in get_all_metadata
    return self.get_metadata(zone, None, debug)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/kumocloud.py", line 154, in get_metadata
    self.serial_number = serial_num_lst[zone]
IndexError: list index out of range

```

**Comment by cjkrolak** [comment]
root cause for error was a bad password.

root cause for confusing traceback was missing authentication validation.  Upon validation error pykumo returns empty list of units, not an exception.  I added a check for empty list as well as a check for index error later in the code, and displayed an intuitive error message.  These enhancements were made to both kumocloud and kumolocal classes.
