### ISSUE TITLE
3m50 socket timeout when reading http data

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#78]
3m50 is working in OFF mode but crashing in heat mode.  Honeywell does not have this same issue.

**Comment by cjkrolak** [comment]
also crashes in cool mode, see attached pic for traceback, failing in get_schedule_heat_sp / get_schedule_cool_sp for a json timeout[](url)
![78_3m50_crash](https://user-images.githubusercontent.com/16019862/126040883-bc880022-199f-48f4-8531-2b2dde49f2a0.png)

**Comment by cjkrolak** [comment]
also happening now in OFF mode:  
Traceback (most recent call last):
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\supervise.py", line 205, in <module>
    main(tstat_type, zone_input)
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\supervise.py", line 94, in main
    current_mode = zone.get_current_mode(
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\thermostat_common.py", line 93, in get_current_mode
    heat_mode = (self.get_system_switch_position() ==
  File "C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor\mmm.py", line 442, in get_system_switch_position
    result = self.device_id.tmode['raw']
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\site-packages\radiotherm\fields.py", line 46, in __get__
    envelope = json.loads(response.read().decode('utf-8'))
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 465, in read
    return self._readall_chunked()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 572, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 555, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 515, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

C:\Users\cjkro\OneDrive\Documents\github\ThermostatSupervisor>

**Comment by cjkrolak** [comment]
I suspect that the socket timeout is being set to 1 sec when discovering the thermostat and this is too short a timeout, currently testing longer timeout value

**Comment by cjkrolak** [comment]
get_current_switch_position and get_display_temp functions are showing this error.

**Comment by cjkrolak** [comment]
problem replicated on raspberry pi client, however failure rate seems a little lower / less frequent, one of two tstats failed overnight vs. both failing almost immediately with dell client.

mitigation efforts to-date have not been successful, suspect it's a socket.timeout from urllib or some http library.

**Comment by cjkrolak** [comment]
raspberrypi-0 failures after session 5 poll 3 and session 1 poll 27

**Comment by cjkrolak** [comment]
radiotherm version 2.1 introduced a 4 second URL timeout, I suspect this timeout is what was causing the intermittent 3m50 timeout I have been seeing.  I will override this timeout to be 10 seconds, which appeared to work OK when run overnight
