### ISSUE TITLE
ValueError: Number of classes, 4, does not match size of target_names, 2. Try specifying the labels parameter

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#800]
observed on pi4 running python 3.11.7 and tf 2.15:

```
ERROR: test_compute_classification_report (__main__.LocalMLTrainEnvironmentTest.test_compute_classification_report)
Verify compute_classification_report().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/mock.py", line 1375, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/github/fish_recognition/tests/ml_train_environment_test.py", line 207, in test_compute_classification_report
    self.ml_train_env.compute_classification_report()
  File "/home/pi/github/fish_recognition/fish_recognition/MLTrainEnvironment.py", line 777, in compute_classification_report
    print(sklm.classification_report(self.true_categories, self.y_pred,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/sklearn/metrics/_classification.py", line 2614, in classification_report
    raise ValueError(
ValueError: Number of classes, 4, does not match size of target_names, 2. Try specifying the labels parameter

----------------------------------------------------------------------

```

**Comment by cjkrolak** [comment]
issue put in wrong repo, closing without fix
