### ISSUE TITLE
Kumocloud: rssi key error

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#804]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 814, in <module>
    tc.print_select_data_from_all_zones(
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1307, in print_select_data_from_all_zones
    wifi_strength = Zone.get_wifi_strength()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 553, in get_wifi_strength
    return float(self.get_parameter("rssi", "rssi"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 297, in get_parameter
    return_val = parent_dict[key]
                 ~~~~~~~~~~~^^^^^
KeyError: 'rssi'
```

**Comment by cjkrolak** [comment]
root cause was empty rssi dict since unit was off for a while, adding default value.
