### ISSUE TITLE
nest: oauthlib.oauth2.rfc6749.errors.InvalidGrantError

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#825]
failures in python 3.13 testing: 3 failures

```
======================================================================
ERROR: test_a_thermostat_basic_checkout (tests.test_nest_integration.FunctionalIntegrationTest.test_a_thermostat_basic_checkout)
Verify thermostat_basic_checkout on target thermostat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 257, in _request
    r = self._client.request(verb, url,
                             allow_redirects=False,
                             data=data)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 528, in request
    url, headers, data = self._client.add_token(
                         ~~~~~~~~~~~~~~~~~~~~~~^
        url, http_method=method, body=data, headers=headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\unittest\mock.py", line 1423, in patched
    return func(*newargs, **newkeywargs)
  File "C:\github\ThermostatSupervisor\tests\unit_test_common.py", line 265, in test_a_thermostat_basic_checkout
    IntegrationTest.Thermostat, IntegrationTest.Zone = tc.thermostat_basic_checkout(
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        api.uip.get_user_inputs(api.uip.zone_name, api.input_flds.thermostat_type),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        self.mod.ThermostatZone,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1224, in thermostat_basic_checkout
    Thermostat, Zone = create_thermostat_instance(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        thermostat_type, zone, ThermostatClass, ThermostatZone
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1189, in create_thermostat_instance
    Thermostat = ThermostatClass(zone, verbose=verbose)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 94, in __init__
    self.devices = self.get_device_data()
                   ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 112, in get_device_data
    self.devices = self.thermostat_obj.get_devices()
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 316, in get_devices
    for device in self._devices:
                  ^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 297, in _devices
    self._devices_value = self._request('GET', '')['devices']
                          ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 274, in _request
    token = self._client.refresh_token(
        ACCESS_TOKEN_URL, **extra)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 496, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request

======================================================================
ERROR: test_print_select_data_from_all_zones (tests.test_nest_integration.FunctionalIntegrationTest.test_print_select_data_from_all_zones)
Verify print_select_data_from_all_zones on target thermostat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 257, in _request
    r = self._client.request(verb, url,
                             allow_redirects=False,
                             data=data)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 528, in request
    url, headers, data = self._client.add_token(
                         ~~~~~~~~~~~~~~~~~~~~~~^
        url, http_method=method, body=data, headers=headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\unittest\mock.py", line 1423, in patched
    return func(*newargs, **newkeywargs)
  File "C:\github\ThermostatSupervisor\tests\unit_test_common.py", line 281, in test_print_select_data_from_all_zones
    ) = tc.print_select_data_from_all_zones(
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        api.uip.get_user_inputs(api.uip.zone_name, api.input_flds.thermostat_type),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        display_battery=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1298, in print_select_data_from_all_zones
    Thermostat, Zone = create_thermostat_instance(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        thermostat_type, zone, ThermostatClass, ThermostatZone, verbose=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\thermostat_common.py", line 1189, in create_thermostat_instance
    Thermostat = ThermostatClass(zone, verbose=verbose)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 94, in __init__
    self.devices = self.get_device_data()
                   ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 112, in get_device_data
    self.devices = self.thermostat_obj.get_devices()
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 316, in get_devices
    for device in self._devices:
                  ^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 297, in _devices
    self._devices_value = self._request('GET', '')['devices']
                          ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 274, in _request
    token = self._client.refresh_token(
        ACCESS_TOKEN_URL, **extra)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 496, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request

======================================================================
ERROR: test_supervise (tests.test_nest_integration.SuperviseIntegrationTest.test_supervise)
Verify supervisor loop on target thermostat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 257, in _request
    r = self._client.request(verb, url,
                             allow_redirects=False,
                             data=data)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 528, in request
    url, headers, data = self._client.add_token(
                         ~~~~~~~~~~~~~~~~~~~~~~^
        url, http_method=method, body=data, headers=headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\unittest\mock.py", line 1423, in patched
    return func(*newargs, **newkeywargs)
  File "C:\github\ThermostatSupervisor\tests\unit_test_common.py", line 416, in test_supervise
    return_status = sup.exec_supervise(debug=True, argv_list=self.unit_test_argv)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\supervise.py", line 113, in exec_supervise
    supervisor(
    ~~~~~~~~~~^
        api.uip.get_user_inputs(api.uip.parent_keys[0], api.input_flds.thermostat_type),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.uip.get_user_inputs(api.uip.parent_keys[0], api.input_flds.zone),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\supervise.py", line 50, in supervisor
    Thermostat = mod.ThermostatClass(zone_num)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 94, in __init__
    self.devices = self.get_device_data()
                   ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\nest.py", line 112, in get_device_data
    self.devices = self.thermostat_obj.get_devices()
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 316, in get_devices
    for device in self._devices:
                  ^^^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 297, in _devices
    self._devices_value = self._request('GET', '')['devices']
                          ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\github\ThermostatSupervisor\..\python-nest\nest\nest.py", line 274, in _request
    token = self._client.refresh_token(
        ACCESS_TOKEN_URL, **extra)
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 496, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
```

**Comment by cjkrolak** [comment]
problem reproduced on 3.13 and 3.12

**Comment by cjkrolak** [comment]
root cause is an expired token.  This is a duplicate of #797.  I added an exception handler message to make this more clear, ideally the code could re-authorize itself (#759) but this is a lower priority.

manual re-auth steps: refer to this page and update access_token.json

https://developers.google.com/nest/device-access/authorize#3-access-token

**Comment by cjkrolak** [comment]
related to #797

**Comment by cjkrolak** [comment]
Token was expired again on 11/28/24, follow sequence in thermostatsupervisor google sheet to generate a new token_cache.json file.
