### ISSUE TITLE
IndexError: list index out of range, kumocloud code called from nest integration test

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#826]
failures in python 3.13 testing: 2 failures

```
======================================================================
ERROR: test_get_all_meta_data (tests.test_nest_integration.FunctionalIntegrationTest.test_get_all_meta_data)
Verify get_all_metadata().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\unittest\mock.py", line 1423, in patched
    return func(*newargs, **newkeywargs)
  File "C:\github\ThermostatSupervisor\tests\unit_test_common.py", line 362, in test_get_all_meta_data
    metadata = self.Thermostat.get_all_metadata(zone=self.Thermostat.zone_name)
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 115, in get_all_metadata
    return self.get_metadata(zone)
           ~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 179, in get_metadata
    zone = self.get_zone_index_from_name()
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 92, in get_zone_index_from_name
    zone_index = [
                 ~
    ...<2 lines>...
        if kumocloud_config.metadata[i]["zone_name"] == self.zone_name
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ][0]
    ~^^^
IndexError: list index out of range

======================================================================
ERROR: test_get_meta_data (tests.test_nest_integration.FunctionalIntegrationTest.test_get_meta_data)
Verify get_metadata().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cjkro\AppData\Local\Programs\Python\Python313\Lib\unittest\mock.py", line 1423, in patched
    return func(*newargs, **newkeywargs)
  File "C:\github\ThermostatSupervisor\tests\unit_test_common.py", line 380, in test_get_meta_data
    metadata = self.Thermostat.get_metadata(
        zone=self.Thermostat.zone_name, trait=trait, parameter=parameter
    )
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 179, in get_metadata
    zone = self.get_zone_index_from_name()
  File "C:\github\ThermostatSupervisor\thermostatsupervisor\kumocloud.py", line 92, in get_zone_index_from_name
    zone_index = [
                 ~
    ...<2 lines>...
        if kumocloud_config.metadata[i]["zone_name"] == self.zone_name
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ][0]
    ~^^^
IndexError: list index out of range
```

**Comment by cjkrolak** [comment]
problem reproduced on 3.13 and 3.12

**Comment by cjkrolak** [comment]
error is not reproducible when running test_nest_integration or test_kumocloud_integration, now testing full unit test suite

**Comment by cjkrolak** [comment]
failures are not reproducible with python 3.13 and full unit test suite.
