### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#83]
error happended on pi4 supervising honeywell:

Traceback (most recent call last):
  File "supervise.py", line 204, in <module>
    main(tstat_type)
  File "supervise.py", line 128, in main
    zone.set_cool_setpoint(zone.get_schedule_cool_sp())
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 409, in set_cool_setpoint
    'SystemSwitch': self.system_switch_position[self.COOL_MODE],
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 135, in submit_control_changes
    return self.pyhtcc.submit_raw_control_changes(self.device_id, data)
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 423, in submit_raw_control_changes
    json_data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cjkrolak** [comment]
another occurrence:
2021-07-19 18:53:40: (session:1, poll:1) COOL MODE [cool deviation] act temp=72.0°F, act humidity=51.0% RH, set point=72, override=66 (temporary)
[log_msg]: message text=Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Subject: honeywell cool deviation alert on zone 0
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

MjAyMS0wNy0xOSAxODo1Mzo0MDogKHNlc3Npb246MSwgcG9sbDoxKSBDT09MIE1PREUgW2Nvb2wg
ZGV2aWF0aW9uXSBhY3QgdGVtcD03Mi4wwrBGLCBhY3QgaHVtaWRpdHk9NTEuMCUgUkgsIHNldCBw
b2ludD03Miwgb3ZlcnJpZGU9NjYgKHRlbXBvcmFyeSkKCmVtYWlsIHNlbnQgZnJvbSBtb2R1bGUg
Jzxtb2R1bGUgJ2VtYWlsX25vdGlmaWNhdGlvbicgZnJvbSAnL2hvbWUvcGkvZ2l0aHViL1RoZXJt
b3N0YXRTdXBlcnZpc29yL2VtYWlsX25vdGlmaWNhdGlvbi5weSc+JyBydW5uaW5nIG9uIHJhc3Bi
ZXJyeXBpICgxMjcuMC4xLjEp

[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!

*** honeywell cool deviation detected on zone 0, reverting thermostat to cool schedule ***

Traceback (most recent call last):
  File "supervise.py", line 206, in <module>
    main(tstat_type, zone_input)
  File "supervise.py", line 129, in main
    zone.set_cool_setpoint(zone.get_schedule_cool_sp())
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 436, in set_cool_setpoint
    'SystemSwitch': self.system_switch_position[self.COOL_MODE],
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 135, in submit_control_changes
    return self.pyhtcc.submit_raw_control_changes(self.device_id, data)
  File "/home/pi/.local/lib/python3.7/site-packages/pyhtcc/pyhtcc.py", line 423, in submit_raw_control_changes
    json_data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cjkrolak** [comment]
root cause was hang between thermostat and TCC site, re-registered thermostat wifi and then app unlocked and error went away.

**Comment by cjkrolak** [comment]
another error occurred on 8/21/21 after 21 sessions, here's the failing output:

2021-08-21 12:02:01: (session:11, poll:45) COOL MODE [following schedule] act temp=72.0°F, act humidity=58.0% RH, set point=72, override=72
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 502, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 168, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 502, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 168, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 2 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 3 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "supervise.py", line 214, in <module>
    main(tstat_type, zone_input)
  File "supervise.py", line 144, in main
    zone.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 540, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408

**Comment by cjkrolak** [comment]
this is a duplicate of #93, closing this issue.
