### ISSUE TITLE
JSON decode error, then missing device

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#93]
Honeywell running off of pi-4:

2021-07-30 06:09:32: (session:31, poll:32) COOL MODE [following schedule] act temp=72.0°F, act humidity=57.0% RH, set point=72, override=72
DEBUG: get_current_mode entrypoint (switch position=3)
2021-07-30 06:19:38: (session:31, poll:33) COOL MODE [following schedule] act temp=72.0°F, act humidity=57.0% RH, set point=72, override=72
DEBUG: get_current_mode entrypoint (switch position=2)
2021-07-30 06:33:05: (session:31, poll:34) OFF MODE [following schedule] act temp=72.0°F, act humidity=57.0% RH
DEBUG: get_current_mode entrypoint (switch position=2)
2021-07-30 06:43:24: (session:31, poll:35) OFF MODE [following schedule] act temp=72.0°F, act humidity=57.0% RH
DEBUG: get_current_mode entrypoint (switch position=2)
2021-07-30 06:53:54: (session:31, poll:36) OFF MODE [following schedule] act temp=72.0°F, act humidity=57.0% RH
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 502, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 168, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 502, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 168, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 2 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 3 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "supervise.py", line 206, in <module>
    main(tstat_type, zone_input)
  File "supervise.py", line 136, in main
    zone.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 540, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408

**Comment by cjkrolak** [comment]
issue still occurring at a low level, Honeywell monitoring on pi4:

2021-09-30 12:35:10: (session:10, poll:101) OFF MODE [following schedule] act temp=74.0°F, act humidity=62.0% RH
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 561, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 192, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 561, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 192, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 2 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 3 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "supervise.py", line 165, in <module>
    main(tstat_type, zone_input)
  File "supervise.py", line 139, in main
    Zone.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 599, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408

**Comment by cjkrolak** [comment]
this error is still happening occasionally on pi4 / honeywell:
2021-12-16 21:23:41: (session:4, poll:11) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33.0%RH, set point=68, tolerance=2, override=68
2021-12-16 21:33:52: (session:4, poll:12) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=33.0%RH, set point=68, tolerance=2, override=68
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 584, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 192, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 584, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 192, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cjkrolak** [comment]
Honeywell & pi4:
2021-12-22 03:09:02: (session:2, poll:116) HEAT_MODE [following schedule] act temp=66.0°F, act humidity=28.0%RH, set point=66.0°F, tolerance=2.0°F, override=66.0°F
DEBUG: self.current_mode=heat
DEBUG in set_mode, target_mode=OFF_MODE, doing nothing
[log_msg]: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb5662bf0>: Failed to establish a new connection: [Errno 110] Connection timed out

**Comment by cjkrolak** [comment]
updated requests from 2.21.0 to 2.26.0 on pi4
updated requests from 2.25.1 to 2.26.0 on cjk laptop

**Comment by cjkrolak** [comment]
changes made:
1. added timing measurement to honeywell.py
2. added 2 second default timeout to TimeoutHTTPAdapter, measurements on both pi4 and laptop are 1.2 to 1.9 (6 sigma).  I'm not sure what the default timeout was set to, so not sure if this will make a difference, need to test for a while.

These changes are being merged to develop but ticket will remain open for extended testing.

**Comment by cjkrolak** [comment]
failure is still happening in pi4/honeywell:
2021-12-30 17:33:57: (session:1, poll:53) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=29% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
2021-12-30 17:44:11: (session:1, poll:54) HEAT_MODE [following schedule] act temp=68.0°F, act humidity=29% RH, set point=68.0°F, tolerance=2.0°F, override=68.0°F
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 639, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 199, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 1 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 639, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 199, in get_zones_info
    data = result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[log_msg]: exception during refresh_zone_info, on trial 2 of 3, probably a connection issue, waiting 30 seconds and then retrying...
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: intermittent JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 3 of 3

email sent from module '<module 'email_notification' from '/home/pi/github/ThermostatSupervisor/email_notification.py'>' running on raspberrypi (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "supervise.py", line 217, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "supervise.py", line 206, in exec_supervise
    supervisor(api.user_inputs["thermostat_type"], api.user_inputs["zone"])
  File "supervise.py", line 167, in supervisor
    Zone.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/honeywell.py", line 678, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408

**Comment by cjkrolak** [comment]
updating pip packages in hopes to resolve this issue:

py4 inventory:
Flask 1.0.2 2.0.2 - updated
psutil 5.5.1 5.9.0 - updated
requests 2.21.0 2.27.1 - updated
simplejson 3.16.0 3.17.6 - updated
urllib3 1.24.1 1.26.8 - updated

**Comment by cjkrolak** [comment]
updated urllib3 and requests libraries did not appear to resolve this issue, added additional timestamp data this week per #395 to hopefully shed light on this issue.  Initial exception is occurring in urllib3 library.

**Comment by cjkrolak** [comment]
this is still an issue that requires resolution:

DEBUG in set_mode, target_mode=OFF_MODE, doing nothing
[log_msg]: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/pi/.local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/pi/.local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 713, in refresh_zone_info
    all_zones_info = self.pyhtcc.get_zones_info()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 210, in get_zones_info
    data = result.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">






<html xmlns="http://www.w3.org/1999/xhtml">

<head><title>
	
Unexpected Error

**Comment by cjkrolak** [comment]
issue still observed occasionally:

```
[log_msg]: message text=Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: honeywell zone 0: fatal JSON decode error during refresh zone
From: cjkrolak2@gmail.com
To: cjkrolak2@gmail.com

refresh_zone_info: trial 11 of 11 at 2023-04-05 08:18:11

email sent from module '<module 'thermostatsupervisor.email_notification' from '/home/pi/github/ThermostatSupervisor/thermostatsupervisor/email_notification.py'>' running on raspberrypi4 (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 133, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 113, in exec_supervise
    supervisor(api.uip.get_user_inputs(api.uip.parent_keys[0],
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 76, in supervisor
    measurement = Zone.supervisor_loop(Thermostat, session_count,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1041, in supervisor_loop
    self.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 770, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408
```

**Comment by cjkrolak** [comment]
another occurrence:
refresh_zone_info: trial 11 of 11 at 2023-04-16 22:54:01

email sent from module '<module 'thermostatsupervisor.email_notification' from '/home/pi/github/ThermostatSupervisor/thermostatsupervisor/email_notification.py'>' running on raspberrypi4 (127.0.1.1)
[log_msg]: smtp connection successful
[log_msg]: email account authorization for account cjkrolak2@gmail.com successful
[log_msg]: mail send was successful
[log_msg]: Email sent!
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 133, in <module>
    exec_supervise(debug=True, argv_list=argv_inputs)
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 113, in exec_supervise
    supervisor(api.uip.get_user_inputs(api.uip.parent_keys[0],
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/supervise.py", line 76, in supervisor
    measurement = Zone.supervisor_loop(Thermostat, session_count,
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/thermostat_common.py", line 1041, in supervisor_loop
    self.refresh_zone_info()
  File "/home/pi/github/ThermostatSupervisor/thermostatsupervisor/honeywell.py", line 770, in refresh_zone_info
    raise pyhtcc.ZoneNotFoundError(f"Missing device: {self.device_id}")
pyhtcc.pyhtcc.ZoneNotFoundError: Missing device: 1457408


```
```

**Comment by cjkrolak** [comment]
according to pyhtcc log, the JSONDecodeError is actually an authorization error message 401 error:

```
2023-04-16 18:38:01,396 - pyhtcc.pyhtcc.py:221 - ERROR - Unable to decode json data returned by GetZoneList. Data was:
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/pi/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by cjkrolak** [comment]
pyhtcc ticket opened to address the JSONDecodeError masking:  https://github.com/csm10495/pyhtcc/issues/10

**Comment by cjkrolak** [comment]
this one was fixed in pyhtcc, closing issue without changes to this app.
